@echo off
setlocal
title TVGun Game Hall
rem === Auto-generated by make-launchers.sh - do not edit ===
rem Pure ASCII on purpose: the launcher bat has a Chinese file name,
rem so we call it through a "*.bat" wildcard in the game directory
rem instead of embedding non-ASCII bytes in this file. Each game
rem directory holds exactly one .bat (the generated launcher).

:menu
cls
echo ============================================
echo            TVGun Game Hall (27 games)
echo ============================================
echo   1. Action Deka
echo   2. After Dark
echo   3. Akuma
echo   4. Aliens Extermination
echo   5. Big Buck Hunter Pro
echo   6. Big Buck Hunter Pro Home
echo   7. Block King Ball Shooter
echo   8. Bug Busters
echo   9. ByonByon
echo  10. Cooper's 9
echo  11. Family Guy Bowling
echo  12. Friction
echo  13. Gashaaaan!!!!
echo  14. Gashaaaan Refill!
echo  15. Ghost Squad Evolution
echo  16. Go Go Strike
echo  17. Haunted Museum
echo  18. Medaru No Gunman
echo  19. Omatsuri Yasan: Ganso Takoyaki
echo  20. Omatsuri Yasan: Kingyo Sukui
echo  21. Point Blank X
echo  22. Primeval Hunt
echo  23. Pull The Trigger!
echo  24. Robin Hood
echo  25. Vampire Night
echo  26. Wartran Troopers
echo  27. Wild West Shootout
echo   0. Exit
echo ============================================
set /p "CHOICE=Enter number and press Enter: "
if "%CHOICE%"=="0" exit /b 0
if "%CHOICE%"=="1" goto g01
if "%CHOICE%"=="2" goto g02
if "%CHOICE%"=="3" goto g03
if "%CHOICE%"=="4" goto g04
if "%CHOICE%"=="5" goto g05
if "%CHOICE%"=="6" goto g06
if "%CHOICE%"=="7" goto g07
if "%CHOICE%"=="8" goto g08
if "%CHOICE%"=="9" goto g09
if "%CHOICE%"=="10" goto g10
if "%CHOICE%"=="11" goto g11
if "%CHOICE%"=="12" goto g12
if "%CHOICE%"=="13" goto g13
if "%CHOICE%"=="14" goto g14
if "%CHOICE%"=="15" goto g15
if "%CHOICE%"=="16" goto g16
if "%CHOICE%"=="17" goto g17
if "%CHOICE%"=="18" goto g18
if "%CHOICE%"=="19" goto g19
if "%CHOICE%"=="20" goto g20
if "%CHOICE%"=="21" goto g21
if "%CHOICE%"=="22" goto g22
if "%CHOICE%"=="23" goto g23
if "%CHOICE%"=="24" goto g24
if "%CHOICE%"=="25" goto g25
if "%CHOICE%"=="26" goto g26
if "%CHOICE%"=="27" goto g27
echo Invalid choice.
pause
goto menu

:g01
call :launch "D:\yinwu\Action Deka\Action Deka\GDK"
goto menu
:g02
call :launch "D:\yinwu\After Dark"
goto menu
:g03
call :launch "D:\yinwu\Akuma\Akuma\data"
goto menu
:g04
call :launch "D:\yinwu\Aliens-Extermination\Aliens-Extermination\DATA"
goto menu
:g05
call :launch "D:\yinwu\Big Bug Hunter Pro\Big Bug Hunter Pro"
goto menu
:g06
call :launch "D:\yinwu\Big Buck Hunter Pro Home\Big Buck Hunter Pro Home"
goto menu
:g07
call :launch "D:\yinwu\Block King Ball Shooter\Block King Ball Shooter"
goto menu
:g08
call :launch "D:\yinwu\Bug Busters\Bug Busters"
goto menu
:g09
call :launch "D:\yinwu\ByonByon\ByonByon\bin"
goto menu
:g10
call :launch "D:\yinwu\Cooper's 9\Cooper's 9"
goto menu
:g11
call :launch "D:\yinwu\Family Guy Bowling\Family Guy Bowling"
goto menu
:g12
call :launch "D:\yinwu\Friction\Friction"
goto menu
:g13
call :launch "D:\yinwu\Gashaaaan!!!!\Gashaaaan!!!!\F24\bin"
goto menu
:g14
call :launch "D:\yinwu\Gashaaaan Refill!\Gashaaaan Refill!\IG2\exec_root"
goto menu
:g15
call :launch "D:\yinwu\Ghost Squad Evolution\Ghost Squad Evolution\vsg_l"
goto menu
:g16
call :launch "D:\yinwu\Go Go Strike\Go Go Strike"
goto menu
:g17
call :launch "D:\yinwu\Haunted Museum\Haunted Museum"
goto menu
:g18
call :launch "D:\yinwu\Medaru No Gunman\Medaru No Gunman\exe"
goto menu
:g19
call :launch "D:\yinwu\Omatsuri Yasan - Ganso Takoyaki\Omatsuri Yasan - Ganso Takoyaki"
goto menu
:g20
call :launch "D:\yinwu\Omatsuri Yasan - Kingyo Sukui\Omatsuri Yasan - Kingyo Sukui"
goto menu
:g21
call :launch "D:\yinwu\Point Blank X\Point Blank X"
goto menu
:g22
call :launch "D:\yinwu\Primeval Hunt\Primeval Hunt\disk0\prog"
goto menu
:g23
call :launch "D:\yinwu\Pull The Trigger\Pull The Trigger"
goto menu
:g24
call :launch "D:\yinwu\Robin Hood\Robin Hood\data"
goto menu
:g25
call :launch "D:\yinwu\Vampire Night\Vampire Night"
goto menu
:g26
call :launch "D:\yinwu\Wartran Troopers\Wartran Troopers\D00\D00\game"
goto menu
:g27
call :launch "D:\yinwu\Wild West Shootout\Wild West Shootout"
goto menu

:launch
for %%F in ("%~1\*.bat") do call "%%F"
exit /b 0
