#!/usr/bin/env bash
# make-launchers.sh - generate one-click launcher bats for the 27 TeknoParrot games.
#
# Usage:
#   ./make-launchers.sh                          # real run: write 启动游戏.bat into each
#                                                # gameDirectory + D:\yinwu\游戏大厅.bat
#   ./make-launchers.sh --dry-run --out <dir>    # test run: write <dir>/<id>.bat + <dir>\hall.bat
#                                                # (game directories are NOT touched)
#
# Notes:
# - JSON parsing uses the venv python (system python on this machine is a stub).
# - Generated .bat files are pure ASCII with CRLF line endings: cmd.exe misreads
#   UTF-8 comments/LF, so all echo/rem text is English.
# - The hall menu is also pure ASCII. The per-game bat file name is Chinese
#   (启动游戏.bat); to keep the menu ASCII we invoke it via a "*.bat" wildcard
#   in the game directory (verified: each gameDirectory contains exactly one bat,
#   the generated launcher). This is codepage-immune, unlike chcp 65001 + BOM.

set -euo pipefail

ROOT="D:/yinwu"
GAMES_DIR="$ROOT/tvgun-bridge/src/TvgunBridge.Core/games"
BRIDGE_EXE_WIN='D:\yinwu\tvgun-bridge\src\TvgunBridge.App\bin\Release\net9.0-windows\TvgunBridge.App.exe'
SETUP_BAT_WIN='D:\yinwu\tvgun-bridge\setup-admin-once.bat'
TP_DIR_WIN='D:\yinwu\1846'
PY="D:/tvgun/.venv/Scripts/python.exe"
LAUNCHER_NAME=$'启动游戏.bat'
HALL_PATH="$ROOT/游戏大厅.bat"

DRY_RUN=0
OUT_DIR=""
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run) DRY_RUN=1; shift ;;
        --out) OUT_DIR="$2"; shift 2 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done
if [ "$DRY_RUN" = "1" ] && [ -z "$OUT_DIR" ]; then
    echo "--dry-run requires --out <dir>" >&2; exit 2
fi
if [ ! -x "$PY" ]; then
    echo "venv python not found: $PY" >&2; exit 2
fi

# Extract id / displayName / teknoParrotProfile / gameDirectory as TSV (sorted by id).
TSV="$("$PY" - "$GAMES_DIR" <<'PYEOF' | tr -d '\r'
import json, glob, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
rows = []
for f in glob.glob(sys.argv[1] + '/*.json'):
    j = json.load(open(f, encoding='utf-8'))
    rows.append((j['id'], j['displayName'], j['teknoParrotProfile'], j['gameDirectory']))
for r in sorted(rows):
    print('\t'.join(r))
PYEOF
)"

COUNT=$(printf '%s\n' "$TSV" | grep -c .)
if [ "$COUNT" != "27" ]; then
    echo "expected 27 games, got $COUNT" >&2; exit 1
fi

# emit_bat <id> <displayName> <profile>  -> writes CRLF ASCII bat to stdout
emit_bat() {
    local id="$1" name="$2" profile="$3"
    {
        printf '@echo off\r\n'
        printf 'setlocal\r\n'
        printf 'rem === Auto-generated by make-launchers.sh - do not edit ===\r\n'
        printf 'rem Game: %s  (adapter: %s, profile: %s)\r\n' "$name" "$id" "$profile"
        printf '\r\n'
        printf 'set "BRIDGE=%s"\r\n' "$BRIDGE_EXE_WIN"
        printf '\r\n'
        printf 'rem 0. Bridge exe must exist (build Release first)\r\n'
        printf 'if not exist "%%BRIDGE%%" (\r\n'
        printf '    echo [ERROR] Bridge exe not found:\r\n'
        printf '    echo         %%BRIDGE%%\r\n'
        printf '    echo Build TvgunBridge.App in Release configuration first.\r\n'
        printf '    pause\r\n'
        printf '    exit /b 1\r\n'
        printf ')\r\n'
        printf '\r\n'
        printf 'rem 1. One-time admin setup check (urlacl + firewall); self-elevate if missing\r\n'
        printf 'netsh http show urlacl | findstr /C:"http://+:8000/" >nul 2>&1\r\n'
        printf 'if errorlevel 1 (\r\n'
        printf '    echo First-run setup needs admin rights once...\r\n'
        printf "    powershell -NoProfile -Command \"Start-Process -FilePath '%s' -Verb RunAs -Wait\"\r\n" "$SETUP_BAT_WIN"
        printf ')\r\n'
        printf '\r\n'
        printf 'rem 2. Kill stale TeknoParrotUi (single-instance mutex would block)\r\n'
        printf 'taskkill /IM TeknoParrotUi.exe /F >nul 2>&1\r\n'
        printf '\r\n'
        printf 'rem 3. Start bridge (auto: ini, input server, injection, borderless, overlay)\r\n'
        printf 'start "" "%%BRIDGE%%" --game %s\r\n' "$id"
        printf '\r\n'
        printf 'rem 4. Give bridge a moment, then launch game via TeknoParrotUi CLI\r\n'
        printf 'timeout /t 3 /nobreak >nul\r\n'
        printf 'cd /d %s\r\n' "$TP_DIR_WIN"
        printf 'start "" TeknoParrotUi.exe --profile=%s\r\n' "$profile"
        printf '\r\n'
        printf 'endlocal\r\n'
    }
}

# emit_hall <tsv> -> writes CRLF ASCII hall menu bat to stdout
emit_hall() {
    local tsv="$1"
    {
        printf '@echo off\r\n'
        printf 'setlocal\r\n'
        printf 'title TVGun Game Hall\r\n'
        printf 'rem === Auto-generated by make-launchers.sh - do not edit ===\r\n'
        printf 'rem Pure ASCII on purpose: the launcher bat has a Chinese file name,\r\n'
        printf 'rem so we call it through a "*.bat" wildcard in the game directory\r\n'
        printf 'rem instead of embedding non-ASCII bytes in this file. Each game\r\n'
        printf 'rem directory holds exactly one .bat (the generated launcher).\r\n'
        printf '\r\n'
        printf ':menu\r\n'
        printf 'cls\r\n'
        printf 'echo ============================================\r\n'
        printf 'echo            TVGun Game Hall (27 games)\r\n'
        printf 'echo ============================================\r\n'
        local i=0 id name profile dir
        while IFS=$'\t' read -r id name profile dir; do
            i=$((i + 1))
            printf 'echo  %2d. %s\r\n' "$i" "$name"
        done <<< "$tsv"
        printf 'echo   0. Exit\r\n'
        printf 'echo ============================================\r\n'
        printf 'set /p "CHOICE=Enter number and press Enter: "\r\n'
        printf 'if "%%CHOICE%%"=="0" exit /b 0\r\n'
        i=0
        while IFS=$'\t' read -r id name profile dir; do
            i=$((i + 1))
            printf 'if "%%CHOICE%%"=="%d" goto g%02d\r\n' "$i" "$i"
        done <<< "$tsv"
        printf 'echo Invalid choice.\r\n'
        printf 'pause\r\n'
        printf 'goto menu\r\n'
        printf '\r\n'
        i=0
        while IFS=$'\t' read -r id name profile dir; do
            i=$((i + 1))
            printf ':g%02d\r\n' "$i"
            printf 'call :launch "%s"\r\n' "$dir"
            printf 'goto menu\r\n'
        done <<< "$tsv"
        printf '\r\n'
        printf ':launch\r\n'
        printf 'for %%%%F in ("%%~1\\*.bat") do call "%%%%F"\r\n'
        printf 'exit /b 0\r\n'
    }
}

if [ "$DRY_RUN" = "1" ]; then
    mkdir -p "$OUT_DIR"
    while IFS=$'\t' read -r id name profile dir; do
        emit_bat "$id" "$name" "$profile" > "$OUT_DIR/$id.bat"
        echo "dry-run: $OUT_DIR/$id.bat"
    done <<< "$TSV"
    emit_hall "$TSV" > "$OUT_DIR/hall.bat"
    echo "dry-run: $OUT_DIR/hall.bat"
else
    while IFS=$'\t' read -r id name profile dir; do
        target="$dir/$LAUNCHER_NAME"
        if [ ! -d "$dir" ]; then
            echo "MISSING DIR: $dir" >&2; exit 1
        fi
        emit_bat "$id" "$name" "$profile" > "$target"
        echo "wrote: $target"
    done <<< "$TSV"
    emit_hall "$TSV" > "$HALL_PATH"
    echo "wrote: $HALL_PATH"
fi
