#!/usr/bin/env bash
# Manual (no-gradle) build chain for the tvgun-tv APK（复刻 D:\tvgun\android\build.sh 模式）。
# Usage: ./build.sh          -> build only, produces tvgun-tv/tvgun-tv.apk
#        ./build.sh install  -> build + adb install -r + launch
#
# 机器无关：自动探测 JDK/SDK；可用环境变量覆盖：
#   JAVAC=<javac 路径>  JAVA11=<java11+ 路径>  ANDROID_SDK=<sdk 根目录>
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/out/build"
PKG="com.tvgun.tv"
MIN_SDK=26

w() { cygpath -w "$1"; }

# ---- JDK 探测（javac 任意版本均可；d8/apksigner 需 Java 11+） ----
pick_first() { for c in "$@"; do [ -x "$c" ] && { echo "$c"; return 0; }; done; return 1; }

JAVAC="${JAVAC:-}"
if [ -z "$JAVAC" ]; then
  JAVAC="$(pick_first \
    "/c/Program Files/Android/Android Studio/jbr/bin/javac.exe" \
    "/c/Program Files/Android/jdk/jdk-8.0.302.8-hotspot/jdk8u302-b08/bin/javac.exe" \
    "$(command -v javac 2>/dev/null || true)")"
fi
[ -n "$JAVAC" ] || { echo "no javac found; set JAVAC=..."; exit 1; }
JBIN="$(dirname "$JAVAC")"

JAVA11="${JAVA11:-}"
if [ -z "$JAVA11" ]; then
  for c in "/c/Program Files/Android/Android Studio/jbr/bin/java.exe" \
           /d/Tools/jdk-17*/bin/java.exe \
           /c/Program\ Files/Android/jdk/*/bin/java.exe \
           "$(command -v java 2>/dev/null || true)"; do
    if [ -x "$c" ]; then
      v="$("$c" -version 2>&1 | head -1)"
      case "$v" in *\"1[1-9]\.*|*\"2[0-9]\.*) JAVA11="$c"; break;; esac
    fi
  done
fi
[ -n "$JAVA11" ] || { echo "no java 11+ found (needed by d8/apksigner); set JAVA11=..."; exit 1; }
J11HOME="$(cd "$(dirname "$JAVA11")/.." && pwd)"

# ---- Android SDK 探测 ----
SDK="${ANDROID_SDK:-${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}}"
if [ -z "$SDK" ]; then
  for u in "${USER:-}" "${USERNAME:-}" "$(basename "$HOME")"; do
    [ -n "$u" ] && [ -d "/c/Users/$u/AppData/Local/Android/Sdk" ] && {
      SDK="/c/Users/$u/AppData/Local/Android/Sdk"; break; }
  done
fi
[ -n "$SDK" ] && [ -d "$SDK" ] || { echo "no Android SDK found; set ANDROID_SDK=..."; exit 1; }
AJAR="$(ls -d "$SDK"/platforms/android-*/android.jar 2>/dev/null | sort -V | tail -1 || true)"
BT="$(ls -d "$SDK"/build-tools/*/ 2>/dev/null | sort -V | tail -1 || true)"
ADB="$SDK/platform-tools/adb.exe"
[ -n "$AJAR" ] || { echo "no android.jar under $SDK/platforms; set ANDROID_SDK=..."; exit 1; }
[ -n "$BT" ] || { echo "no build-tools under $SDK; set ANDROID_SDK=..."; exit 1; }
BT="${BT%/}"
TARGET_SDK="$(basename "$(dirname "$AJAR")" | sed 's/android-//')"

echo "javac:  $JAVAC"
echo "java11: $JAVA11"
echo "sdk:    $SDK (platform android-$TARGET_SDK, build-tools $(basename "$BT"))"

# javac 参数：JDK9+ 用 --release 8，JDK8 用 -source/-target
if "$JAVAC" --release 8 -version >/dev/null 2>&1; then
  JAVAC_REL=(--release 8)
else
  JAVAC_REL=(-source 1.8 -target 1.8)
fi

export JAVA_HOME="$(w "$J11HOME")"
export PATH="$(dirname "$JAVA11"):$PATH"

mkdir -p "$OUT/classes" "$OUT/dex" "$OUT/gen/com/tvgun/tv"

# ---- 版本戳：git describe 嵌入 APK（防版本错配） ----
GDESCRIBE="$(git -C "$ROOT" describe --always --dirty --tags 2>/dev/null || echo nogit)"
cat > "$OUT/gen/com/tvgun/tv/Version.java" <<EOF
package com.tvgun.tv;
/** Generated by build.sh — do not edit or commit. */
public final class Version {
    public static final String DESCRIBE = "$GDESCRIBE";
    private Version() {}
}
EOF
echo "version: $GDESCRIBE"

echo "==> [1/7] debug keystore"
if [ ! -f "$ROOT/debug.keystore" ]; then
  KEYTOOL="$(pick_first "$(dirname "$JAVAC")/keytool.exe" "$(dirname "$JAVA11")/keytool.exe")"
  "$KEYTOOL" -genkeypair -keystore "$(w "$ROOT/debug.keystore")" \
    -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass android -keypass android \
    -dname "CN=Android Debug,O=Android,C=US"
else
  echo "    (keystore exists, skip)"
fi

echo "==> [2/7] aapt2 link"
rm -f "$OUT/unsigned.apk"
"$BT/aapt2.exe" link -o "$(w "$OUT/unsigned.apk")" \
  -I "$(w "$AJAR")" \
  --manifest "$(w "$ROOT/AndroidManifest.xml")" \
  --min-sdk-version "$MIN_SDK" --target-sdk-version "$TARGET_SDK"

echo "==> [3/7] javac"
rm -rf "$OUT/classes"; mkdir -p "$OUT/classes"
SRCS=()
while IFS= read -r f; do SRCS+=("$(w "$f")"); done < <(find "$ROOT/src" "$OUT/gen" -name '*.java')
"$JAVAC" "${JAVAC_REL[@]}" -encoding UTF-8 \
  -classpath "$(w "$AJAR")" -d "$(w "$OUT/classes")" "${SRCS[@]}"

echo "==> [4/7] d8"
rm -rf "$OUT/dex"; mkdir -p "$OUT/dex"
CLASSES=()
while IFS= read -r f; do CLASSES+=("$(w "$f")"); done < <(find "$OUT/classes" -name '*.class')
"$BT/d8.bat" --min-api "$MIN_SDK" --lib "$(w "$AJAR")" --output "$(w "$OUT/dex")" "${CLASSES[@]}"

echo "==> [5/7] add classes.dex to apk"
cp "$OUT/unsigned.apk" "$OUT/withdex.apk"
JARBIN="$(pick_first "$(dirname "$JAVAC")/jar.exe" "$(dirname "$JAVA11")/jar.exe")"
(cd "$OUT/dex" && "$JARBIN" uf "$(w "$OUT/withdex.apk")" classes.dex)

echo "==> [6/7] zipalign"
"$BT/zipalign.exe" -f 4 "$(w "$OUT/withdex.apk")" "$(w "$OUT/aligned.apk")"

echo "==> [7/7] apksigner sign"
"$BT/apksigner.bat" sign \
  --ks "$(w "$ROOT/debug.keystore")" \
  --ks-pass pass:android --key-pass pass:android \
  --out "$(w "$ROOT/tvgun-tv.apk")" "$(w "$OUT/aligned.apk")"

echo "Built: $ROOT/tvgun-tv.apk"

if [ "${1:-}" = "install" ]; then
  echo "==> adb install"
  "$ADB" install -r "$(w "$ROOT/tvgun-tv.apk")"
  echo "==> am start"
  "$ADB" shell am start -n "$PKG/.MainActivity"
fi
